---
title: "DHS_graph"
author: "Shan Jiang"
date: "9/13/2019"
output: 
  pdf_document:
     toc: true
     number_sections: true
     highlight: tango
  
---

## Table 1: Bar plot 

```{r}
library(tidyverse)
library(ggplot2)
```

```{r echo=TRUE}
df1 = readxl::read_xlsx("./DHS/DHS_dv.xlsx", sheet = "table1")  
df1 = df1 %>%   filter(Percentage != "N")

# Draw plot
ggplot(df1, aes(fill= factor(Status), y=Percentage, x= reorder(Wealth, Percentage))) + 
    geom_bar(position="dodge", stat="identity") +
      scale_y_continuous(labels = function(x) paste0(x, "%")) +
      coord_flip() +
      labs(title="Wealth Index by Migration Status", 
      subtitle="Urban Residents VS. Rural-Urban Migrants", 
      caption="Data source: DHS 2007") +  scale_fill_manual(values = c("#a1d99b", "#31a354")) +
      geom_text(aes(label = round(Percentage, 1)), position = position_dodge(1.1), 
                  vjust = 1.0, color = "black", size = 3.4) +
      theme(axis.text.x = element_text(angle=45, vjust=0.6)) + 
      theme_minimal() +
        theme(axis.title = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor = element_blank(),
              legend.position = c(2,2), legend.justification = c(1,1),
              legend.background = element_blank(),
              legend.direction="horizontal",
              legend.title = element_blank(),
              plot.title = element_text(size = 20, margin = margin(b = 10)),
              plot.subtitle = element_text(size = 12, color = "darkslategrey", 
                                           margin = margin(b = 25)),
              plot.caption = element_text(size = 8, margin = margin(t = 5), 
                                          color = "grey70", hjust = 0))
      
```


## Table 3: Lollipop plot 

```{r}
df2 = readxl::read_xlsx("./DHS/DHS_dv.xlsx", sheet = "table3")  
  
ggplot(df2, 
       aes(x=reorder(`Toilet Usage`, Percentage), y= Percentage, fill =`Toilet Usage` ))  + 
    geom_bar(position="dodge", stat="identity") +
   labs(title="Types of Toilet Facilities in Bangladesh", 
       caption="Data source: DHS 2007") + 
  theme(axis.text.x = element_text(vjust=0.6)) +
    geom_text(aes(label = round(Percentage, 1)), 
                  position = position_dodge(3.1), 
                  vjust = 1.88, color = "black", 
                   size = 3.2) +
  theme_minimal() +
        theme(axis.title = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor = element_blank()) +
      scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
      scale_y_continuous(labels = function(x) paste0(x, "%"))

  
# Plot
ggplot(df2, 
       aes(x=reorder(`Toilet Usage`, Percentage), y= Percentage)) +
  geom_point(size=3) + 
  geom_segment(aes(x=`Toilet Usage`,
                   xend= `Toilet Usage`,
                   y=0, 
                   yend=Percentage)) + 
  labs(title="Types of Toilet Facilities in Bangladesh", 
       caption="Data source: DHS 2007") + 
  theme(axis.text.x = element_text(vjust=0.6)) +
    geom_text(aes(label = round(Percentage, 1)), 
                  position = position_dodge(3.1), 
                  vjust = 1.88, color = "black", 
                  size = 3.2) +
  theme_minimal() +
        theme(axis.title = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor = element_blank()) +
      scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
      scale_y_continuous(labels = function(x) paste0(x, "%"))


```


## Table 6:  Types of Toilet Facilities in Bangladesh by barplot

```{r}
library(tidyverse)
library(viridis)
library(gridExtra)
library(ggrepel)
library(plotly)

df3 = readxl::read_xlsx("./DHS/DHS_dv.xlsx", sheet = "table6") 

# Plot
ggplot(df3, aes(x= City, y= Percentage)) +
    geom_point(aes(color = Toilet, size = Percentage), alpha=0.5) +
    scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    scale_size(range = c(1.5, 14), name="Percentage (%)") +
    theme(legend.position="right") + 
    labs(title="Types of Toilet Facilities in Bangladesh", 
         caption="Data source: DHS 2007") + 
    geom_text(aes(label = round(Percentage, 1)), position = position_dodge(1.1), 
                  vjust = 1.0, color = "black",  size = 2.2) +
        theme_minimal() 


ggplot(df3, aes(x= City, y= Percentage, group = Toilet,
                fill= Toilet)) + 
    geom_bar(position="dodge", stat="identity") +
    labs(title="Types of Toilet Facilities in Bangladesh", 
       caption="Data source: DHS 2007") + 
    scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    theme(legend.position="right") + 
    labs(title="Types of Toilet Facilities in Bangladesh", 
         caption="Data source: DHS 2007") + 
    geom_text(aes(label = round(Percentage, 1)), position = position_dodge(1.1), 
                  vjust = 1.4, color = "black",size = 3.4) +
        theme_minimal() +
      scale_y_continuous(labels = function(x) paste0(x, "%"))

```


